### ISSUE TITLE
I don't understand something.

### ISSUE THREAD

**Issue by Paradox75831004** [LouisSilva/LethalCompanyHarpGhost#4]
He doesn't kill, does he? You just throw a flash grenade - he drops the item - after which he stands afk and can't do anything. I checked from my build and without mods, with only this one monster, created it through LethalDev on the EXP map. (Maybe I'm doing something wrong, but I'm interested in this mod)

**Comment by LouisSilva** [comment]
He does kill. After you provoke him by making too much noise near him/attacking him/stunning him, he should drop the harp and pretty much turn into a glorified thumper.

The reason he probably stood there afk for a while is because I think the stun timer is insanely high by accident. Also you have to be inside the facility / mansion or whatever (not outside or in the LethalDev test room because its still technically outside the map) for it to work. I haven't bothered to fix it yet because he doesn't spawn outside naturally anyway.
